export interface Estudiante {
  EST_ID: string;
    EST_DNI: string;
    EST_NOM: string;
    EST_NOM2: string;
    EST_APE: string;
    EST_APE2: string;
    EST_FECH_NAC: Date;
    EST_GEN: string;
    EST_PRV: string;
    EST_CAN: string;
    EST_PARR: string;
    EST_DIR: string;
    EST_NAC: string;
    EST_ETN: string;
    EST_NAC_ETN: string;
    EST_COM_ETN: string;
    EST_COD_ELE: string;
    EST_NEC_ASO_DIS: boolean;
    EST_NEC_NO_ASO_DIS: boolean;
    EST_ENF_CAT: boolean;
    EST_NUM_CONA: string;
    EST_INTE: boolean;
    EST_TV: boolean;
    EST_RAD: boolean;
    EST_PC: boolean;
    EST_CEL: boolean;
    REPR_ID: string;
    REL_EST_REP: string;
    ESTADO: boolean;
    CREADOR_ID: string;
    FECHA_CREACION?: Date | undefined;
}